// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_rxg2ZxyiTOasZRjFRYrYvd2i27th_Eo',
    appId: '1:75010989789:web:fe901b63a96d21c1890534',
    messagingSenderId: '75010989789',
    projectId: 'swiffy-paw-friends',
    authDomain: 'swiffy-paw-friends.firebaseapp.com',
    storageBucket: 'swiffy-paw-friends.appspot.com',
    measurementId: 'G-M8D87BDK0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3cc4CTER2EaojI4FKFWibtnqT3rE-T2A',
    appId: '1:75010989789:android:33e76cb39a74e70b890534',
    messagingSenderId: '75010989789',
    projectId: 'swiffy-paw-friends',
    storageBucket: 'swiffy-paw-friends.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQUyvdmJSfEMTBHlgEfuwxomCHJTE5csY',
    appId: '1:75010989789:ios:9471e31d9351bfec890534',
    messagingSenderId: '75010989789',
    projectId: 'swiffy-paw-friends',
    storageBucket: 'swiffy-paw-friends.appspot.com',
    iosBundleId: 'com.example.pawFriendsWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQUyvdmJSfEMTBHlgEfuwxomCHJTE5csY',
    appId: '1:75010989789:ios:9471e31d9351bfec890534',
    messagingSenderId: '75010989789',
    projectId: 'swiffy-paw-friends',
    storageBucket: 'swiffy-paw-friends.appspot.com',
    iosBundleId: 'com.example.pawFriendsWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_rxg2ZxyiTOasZRjFRYrYvd2i27th_Eo',
    appId: '1:75010989789:web:d97310f6264fd154890534',
    messagingSenderId: '75010989789',
    projectId: 'swiffy-paw-friends',
    authDomain: 'swiffy-paw-friends.firebaseapp.com',
    storageBucket: 'swiffy-paw-friends.appspot.com',
    measurementId: 'G-XES1B2F10L',
  );
}
